include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/.test_coverage.dart
    - tools/*

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_required_param: error
    missing_return: error
    parameter_assignments: warning
    todo: ignore
    top_level_function_literal_block: ignore

linter:
  rules:
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    always_use_package_imports: false
    avoid_as: false
    avoid_annotating_with_dynamic: false
    avoid_catches_without_on_clauses: false
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    avoid_types_on_closure_parameters: false
    cascade_invocations: false
    close_sinks: false
    diagnostic_describe_all_properties: false
    flutter_style_todos: false
    omit_local_variable_types: false
    prefer_constructors_over_static_methods: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    sort_constructors_first: false
    sort_pub_dependencies: false
    unnecessary_final: false