include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - tools/*

linter:
  rules:
    always_put_required_named_parameters_first: false
    omit_local_variable_types: false
    avoid_classes_with_only_static_members: false
    non_constant_identifier_names: false

    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: true