include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/.test_coverage.dart
    - tools/*

linter:
  rules:
    omit_local_variable_types: false
    avoid_classes_with_only_static_members: false

    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: true