name: lh5801
version: 0.1.0
description: Sharp LH5801 8-bit Microprocessor emulator.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/lh5801
issue_tracker: https://github.com/cbonello/lh5801/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  lint: ^1.2.0
  test: ^1.14.0
