name: lh5801
version: 0.3.0
description: Sharp LH5801 8-bit Microprocessor emulator.
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/lh5801
issue_tracker: https://github.com/cbonello/lh5801/issues
publish_to: none

executables:
  lh5801: lh5801

environment:
  sdk: '>=3.10.0 <4.0.0'

dev_dependencies:
  benchmark_harness: ^2.4.0
  coverage: ^1.12.0
  lints: ^6.0.0
  mocktail: ^1.0.0
  test: ^1.30.0
