name: lh5801
version: 0.3.0
description: Sharp LH5801 8-bit Microprocessor emulator.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/lh5801
issue_tracker: https://github.com/cbonello/lh5801/issues
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.14.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  build_runner: ^2.0.0
  freezed: ^0.14.0
  lint: ^1.6.0
  mocktail: ^0.1.0
  test: ^1.17.0
  test_cov: ^1.0.0
