name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pub get

      - name: Run Tests
        run: |
          pub global activate test_coverage
          export PATH=$PATH:$HOME/.pub-cache/bin
          test_coverage

    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: coverage/lcov.info
