name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dart-lang/setup-dart@v2
      with:
        sdk: stable

    - name: Install dependencies
      run: dart pub get

    - name: Analyze
      run: dart analyze

    - name: Run tests with coverage
      run: dart test --coverage=coverage

    - name: Convert coverage to lcov
      run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        files: coverage/lcov.info
