name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test_coverage --no-badge
    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: coverage/lcov.info
